USE [master]
GO
/****** Object:  Database [MTG]    Script Date: 2/6/2021 20:19:55 ******/
CREATE DATABASE [MTG]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MTG', FILENAME = N'Z:\Program Files\MSSQL15.MSSQLSERVER\MSSQL\DATA\MTG.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MTG_log', FILENAME = N'Z:\Program Files\MSSQL15.MSSQLSERVER\MSSQL\DATA\MTG_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [MTG] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MTG].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MTG] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MTG] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MTG] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MTG] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MTG] SET ARITHABORT OFF 
GO
ALTER DATABASE [MTG] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MTG] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MTG] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MTG] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MTG] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MTG] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MTG] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MTG] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MTG] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MTG] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MTG] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MTG] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MTG] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MTG] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MTG] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MTG] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [MTG] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MTG] SET RECOVERY FULL 
GO
ALTER DATABASE [MTG] SET  MULTI_USER 
GO
ALTER DATABASE [MTG] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MTG] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MTG] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MTG] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MTG] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MTG] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MTG', N'ON'
GO
ALTER DATABASE [MTG] SET QUERY_STORE = OFF
GO
USE [MTG]
GO
/****** Object:  Table [dbo].[Deposito]    Script Date: 2/6/2021 20:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Deposito](
	[DepositoId] [int] NOT NULL,
	[Nombre] [nvarchar](max) NULL,
 CONSTRAINT [PK_Deposito] PRIMARY KEY CLUSTERED 
(
	[DepositoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Login]    Script Date: 2/6/2021 20:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Login](
	[LoginId] [int] NOT NULL,
	[password] [nvarchar](max) NULL,
	[usuario] [nvarchar](max) NULL,
 CONSTRAINT [PK_Login] PRIMARY KEY CLUSTERED 
(
	[LoginId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Movimiento]    Script Date: 2/6/2021 20:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Movimiento](
	[MovimientoId] [int] IDENTITY(1,1) NOT NULL,
	[Cantidad] [int] NOT NULL,
	[Desde_depo] [int] NOT NULL,
	[Hasta_depo] [int] NOT NULL,
	[Id_realizo] [int] NOT NULL,
	[ProductosId] [int] NOT NULL,
	[fecha_hora] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Movimiento] PRIMARY KEY CLUSTERED 
(
	[MovimientoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Productos]    Script Date: 2/6/2021 20:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Productos](
	[ProductosId] [int] NOT NULL,
	[cantidad] [int] NOT NULL,
	[detalle] [nvarchar](max) NULL,
	[sub_descripcion] [nvarchar](max) NULL,
 CONSTRAINT [PK_Productos] PRIMARY KEY CLUSTERED 
(
	[ProductosId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Stock]    Script Date: 2/6/2021 20:19:55 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Stock](
	[StockId] [int] NOT NULL,
	[Cantidad] [int] NOT NULL,
	[DepositoId] [int] NOT NULL,
	[ProductosId] [int] NOT NULL,
	[fecha_hora] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Stock] PRIMARY KEY CLUSTERED 
(
	[StockId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Movimiento_ProductosId]    Script Date: 2/6/2021 20:19:55 ******/
CREATE NONCLUSTERED INDEX [IX_Movimiento_ProductosId] ON [dbo].[Movimiento]
(
	[ProductosId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Stock_DepositoId]    Script Date: 2/6/2021 20:19:55 ******/
CREATE NONCLUSTERED INDEX [IX_Stock_DepositoId] ON [dbo].[Stock]
(
	[DepositoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Stock_ProductosId]    Script Date: 2/6/2021 20:19:55 ******/
CREATE NONCLUSTERED INDEX [IX_Stock_ProductosId] ON [dbo].[Stock]
(
	[ProductosId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Movimiento]  WITH CHECK ADD  CONSTRAINT [FK_Movimiento_Productos_ProductosId] FOREIGN KEY([ProductosId])
REFERENCES [dbo].[Productos] ([ProductosId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Movimiento] CHECK CONSTRAINT [FK_Movimiento_Productos_ProductosId]
GO
ALTER TABLE [dbo].[Stock]  WITH CHECK ADD  CONSTRAINT [FK_Stock_Deposito_DepositoId] FOREIGN KEY([DepositoId])
REFERENCES [dbo].[Deposito] ([DepositoId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Stock] CHECK CONSTRAINT [FK_Stock_Deposito_DepositoId]
GO
ALTER TABLE [dbo].[Stock]  WITH CHECK ADD  CONSTRAINT [FK_Stock_Productos_ProductosId] FOREIGN KEY([ProductosId])
REFERENCES [dbo].[Productos] ([ProductosId])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Stock] CHECK CONSTRAINT [FK_Stock_Productos_ProductosId]
GO
USE [master]
GO
ALTER DATABASE [MTG] SET  READ_WRITE 
GO
